/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DailiesIndexRouteImport } from './routes/dailies/index'
import { Route as DailyNewRouteImport } from './routes/daily/new'
import { Route as DailyDailyIdRouteImport } from './routes/daily/$dailyId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailiesIndexRoute = DailiesIndexRouteImport.update({
  id: '/dailies/',
  path: '/dailies/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyNewRoute = DailyNewRouteImport.update({
  id: '/daily/new',
  path: '/daily/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyDailyIdRoute = DailyDailyIdRouteImport.update({
  id: '/daily/$dailyId',
  path: '/daily/$dailyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/daily/$dailyId': typeof DailyDailyIdRoute
  '/daily/new': typeof DailyNewRoute
  '/dailies/': typeof DailiesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/daily/$dailyId': typeof DailyDailyIdRoute
  '/daily/new': typeof DailyNewRoute
  '/dailies': typeof DailiesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/daily/$dailyId': typeof DailyDailyIdRoute
  '/daily/new': typeof DailyNewRoute
  '/dailies/': typeof DailiesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/daily/$dailyId'
    | '/daily/new'
    | '/dailies/'
    | '/dashboard/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/daily/$dailyId'
    | '/daily/new'
    | '/dailies'
    | '/dashboard'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/daily/$dailyId'
    | '/daily/new'
    | '/dailies/'
    | '/dashboard/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DailyDailyIdRoute: typeof DailyDailyIdRoute
  DailyNewRoute: typeof DailyNewRoute
  DailiesIndexRoute: typeof DailiesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dailies/': {
      id: '/dailies/'
      path: '/dailies'
      fullPath: '/dailies/'
      preLoaderRoute: typeof DailiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/new': {
      id: '/daily/new'
      path: '/daily/new'
      fullPath: '/daily/new'
      preLoaderRoute: typeof DailyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$dailyId': {
      id: '/daily/$dailyId'
      path: '/daily/$dailyId'
      fullPath: '/daily/$dailyId'
      preLoaderRoute: typeof DailyDailyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DailyDailyIdRoute: DailyDailyIdRoute,
  DailyNewRoute: DailyNewRoute,
  DailiesIndexRoute: DailiesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
